version: "3.8"
services:
  coai-mysql:
    image: mysql:latest
    container_name: coai-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatnio
      MYSQL_USER: chatnio
      MYSQL_PASSWORD: chatnio123456
      TZ: Asia/Shanghai
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - coai-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  coai-redis:
    image: redis:latest
    container_name: coai-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    networks:
      - coai-network

  chatnio:
    image: programzmh/chatnio:stable
    container_name: chatnio
    restart: always
    expose:
      - "8094"
    depends_on:
      coai-mysql:
        condition: service_healthy
      coai-redis:
        condition: service_started
    environment:
      MYSQL_HOST: coai-mysql
      MYSQL_USER: chatnio
      MYSQL_PASSWORD: chatnio123456
      MYSQL_DB: chatnio
      REDIS_HOST: coai-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      SERVE_STATIC: "true"
    volumes:
      - ./config:/config
      - ./logs:/logs
      - ./storage:/storage
    networks:
      - coai-network

networks:
  coai-network:
    driver: bridge
